### ISSUE TITLE
Unhandled exception starting ambermoon.net

### ISSUE THREAD

**Issue by Thallyrion** [Pyrdacor/Ambermoon.net#1]
Hi,

trying to start ambermoon.net. I placed the EXE in the amberfiles directory and at starting i get the following exception:
![ambermoon-net error](https://user-images.githubusercontent.com/69513157/89893314-5f821180-dbd8-11ea-90be-3c02a3350783.png)

**Comment by Pyrdacor** [comment]
Do you have the file Palettes.amb inside the amberfiles directory?

**Comment by Thallyrion** [comment]
Yes of course. Game is fully working. It is my WinUAE game directory where
i do actually play the game.

Am Di., 11. Aug. 2020 um 13:43 Uhr schrieb Pyrdacor <
notifications@github.com>:

**Comment by Pyrdacor** [comment]
Ah ok I found the bug. Will fix it soon.

You can use the following workaround:

Go to your app data folder (you can enter "%APPDATA%" in CMD or Windows Explorer). If there is no folder called "Ambermoon", create it. Go into the folder "Ambermoon". If there is no file "ambermoon.cfg", create it as a text file. This is the main configuration file in JSON format. It looks like this:

```json
{
    "Width": 1280,
    "Height": 800,
    "Fullscreen": false,
    "DataPath": "C:\\path\\to\\amberfiles\\directory"
}
```

Enter the path to the amberfiles directory for DataPath. Use double backslash for path delimiters. This should work.

**Comment by Pyrdacor** [comment]
@Thallyrion Should be fixed in v1.0.3. Download link was added on main page or download it [here](https://github.com/Pyrdacor/Ambermoon.net/releases/download/v1.0.3/Ambermoon.net-Windows.zip).

**Comment by Thallyrion** [comment]
The following steps i did:

path appdata\roaming -> created dir Ambermoon -> created ambermoon.cfg with
following parameters

{
    "Width": 1280,
    "Height": 800,
    "Fullscreen": false,
    "DataPath": "E:\\Daten\\Amiga\\WinUAE\\Spiele\\Ambermoon\\Amberfiles"
}

Another problem occurred. I think the problem is a hardcoded path.
[image: ambermoon-net error 2.png]

Am Di., 11. Aug. 2020 um 13:55 Uhr schrieb Pyrdacor <
notifications@github.com>:

**Comment by Thallyrion** [comment]
I have placed the amberfiles now in the coded (C:\projects ...) directory
and the its working fine now.

Great Project. Ambermoon is one of my all time favourites. So if you ever
need something testet, let me know. Glad if i can be of help.

Am Di., 11. Aug. 2020 um 14:21 Uhr schrieb Thallyrion <
rebell311@googlemail.com>:

**Comment by Thallyrion** [comment]
Me again ;)

Just tested v1.03 and hardcoded path problem still exists

Am Di., 11. Aug. 2020 um 14:32 Uhr schrieb Thallyrion <
rebell311@googlemail.com>:

**Comment by Pyrdacor** [comment]
I can't view the last image for some reason. But I guess it is my locale development directory. I checked the code. It should no longer be inside the code. Please delete the ambermoon.cfg and re-test. Maybe the path was updated to "C:\projects\..." there.

**Comment by Pyrdacor** [comment]
> Great Project. Ambermoon is one of my all time favourites. So if you ever need something testet, let me know. Glad if i can be of help.

Thank you very much. It is my all time favorite as well. I can need a helping hand for sure. At this state there are a lot of bugs and not working things so it is a bit early for extensive testing I guess. But I will come back to you later if this is ok.

**Comment by Thallyrion** [comment]
Sure thing, just let me know when there is something to do.
I checked my Ambermoon.cfg it is not updated. The path i entered is still
in it.
v1.03 still has the problem with the path
this error occurres

Am Di., 11. Aug. 2020 um 14:42 Uhr schrieb Pyrdacor <
notifications@github.com>:

**Comment by Pyrdacor** [comment]
Hm it works on my end without problems and I don't have data in "C:\projects\..." either. Can you test with v1.0.4 please? Make sure to remove the config file beforehand.

**Comment by Thallyrion** [comment]
No change for me. Still exactly the same problem with 1.04
I have deleted the config file in appdata\ambermoon

e:\Daten\Amiga\WinUAE\Spiele\Ambermoon\Amberfiles>ambermoon.net
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a
part of the path 'C:\Projects\ambermoon.net\AM2_CPU'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare
share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess
access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess
access, FileShare share, Int32 bufferSize)
   at System.IO.File.ReadAllBytes(String path)
   at Ambermoon.Data.Legacy.ExecutableDeploder.Deplode(IDataReader
dataReader)
   at Ambermoon.Data.Legacy.ItemManager..ctor(IGameData gameData,
IItemReader itemReader)
   at Ambermoon.GameWindow.Window_Load()
   at Silk.NET.Windowing.Desktop.GlfwWindow.Initialize()
   at Silk.NET.Windowing.Common.WindowExtensions.Run(IView view)
   at Ambermoon.GameWindow.Run(Configuration configuration)
   at Ambermoon.Program.Main()


If i put the files in the path the program searches for it is working fine
'C:\Projects\ambermoon.net\

PS. Ich glaube wir können auch auf Deutsch schreiben? ;)

Am Di., 11. Aug. 2020 um 15:42 Uhr schrieb Pyrdacor <
notifications@github.com>:

**Comment by Thallyrion** [comment]
So schneller Nachtrag. Aus irgendeinem Grund funktioniert es jetzt. Habe
mal das komplette ambermoon vz in appdata gelöscht. Vielleicht war es
vorher irgendein cache problem. Aber dafür vllt noch etwas anderes, das
aber wahrscheinlich keine hohe priorität hat.
Habe mal probiert ob es auch von den ADFs spielbar ist und es gab folgenden
fehler:

Unhandled exception. System.IO.IOException: Invalid ADF file format.
Supported is only AmigaDOS 1.2 format (OFS)
   at Ambermoon.Data.Legacy.ADFReader.ReadADF(Stream stream)
   at Ambermoon.Data.Legacy.GameData.Load(String folderPath)
   at Ambermoon.GameWindow.Window_Load()
   at Silk.NET.Windowing.Desktop.GlfwWindow.Initialize()
   at Silk.NET.Windowing.Common.WindowExtensions.Run(IView view)
   at Ambermoon.GameWindow.Run(Configuration configuration)
   at Ambermoon.Program.Main()

Am Di., 11. Aug. 2020 um 17:36 Uhr schrieb Thallyrion <
rebell311@googlemail.com>:

**Comment by Pyrdacor** [comment]
Strange. Ich bin zwar auch aus Deutschland, aber ich antworte mal englisch falls das auch für andere relevant ist:

I only coded a very rudimentary ADF reader which could read the ADF files I had (as well as the Settlers I ADFs for my other project). There are multiple file formats for ADFs. Some are more complicated and there is no support yet. Maybe you can send your ADFs to me via mail: trobt@web.de

Then I can try to add support. Maybe the ADFs use a newer format. Or they are corrupt.

**Comment by Pyrdacor** [comment]
Ok ADF files can now (v1.0.5) be loaded with any format (OFS - old file system and FFS - fast file system) as well as with international mode (INTL) or directory cache (DIRC). International mode is not tested yet but should be not relevant to Ambermoon at all.

I checked your ADF files. Only disk i (music, outro, etc) used the FFS format, the rest used OFS. But as I said you will be able to load them now.

**Comment by Thallyrion** [comment]
Very nice :) I will follow the development closely then. Already explored
the world a bit just to see how it's working. But as this is an early stage
i guess it is not yet time for a report.

Am Mi., 12. Aug. 2020 um 10:21 Uhr schrieb Pyrdacor <
notifications@github.com>:

**Comment by Pyrdacor** [comment]
Metibor found another issue where the "C:\Projects\..." stuff might have caused problems. This should be fixed in v1.0.6 though.

**Comment by Pyrdacor** [comment]
Hi again. Can you please tell me where your Ambermoon ADF files are from and what version that really is?

I am decoding the AM2_CPU file and it is structurally identical between the german versions 1.01 and 1.05. So my hope was that I can use fixed offsets to extract some data. But your files (1.04 you said) are different very quickly. So what kind of version is this? Even the english 1.07 version has more identical parts to the other german versions than your 1.04 version. :D

**Comment by Thallyrion** [comment]
Hi,

the version i sent you is from this place:
http://thalion.exotica.org.uk/games/ambermoon/credits/credits.html
it's labeled 1.05 there but actually is 1.04 i think.

Am Do., 20. Aug. 2020 um 00:46 Uhr schrieb Pyrdacor <
notifications@github.com>:
