### ISSUE TITLE
[Bug report] Game does not start under Mac OS Monterey (12.1)

### ISSUE THREAD

**Issue by Tosh79** [Pyrdacor/Ambermoon.net#285]
**Describe the bug**
Upon launching the downloaded Ambermoon.net bundle, the game does not start, showing this error message (when launch from console):

> The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x6000027d9e30 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}

**To Reproduce**
1. Download the newest version ambermoon.net
2. Doubleclick the launcher icon

**Expected behavior**
The game starts without any error messages.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey (12.1)

**Additional context**
It does seem, that even older versions (tried it with 1.3) do not start.

**Comment by Pyrdacor** [comment]
Thanks for your report. 1.4 seems to have problems on all systems and I am working on it.

**Comment by Pyrdacor** [comment]
Can you please test with this updated version: https://github.com/Pyrdacor/Ambermoon.net/releases/download/v1.4.0/Ambermoon.net-Mac-Bundle.zip

**Comment by ZandigSlaytanic** [comment]
Just a few minutes ago I noticed this same problem of the game opening and closing straight away in the Windows version. So I headed back here to submit a report. Good to see it's being looked into.

**Comment by Pyrdacor** [comment]
I know the reason but it will take some time. I guess I could fix the 1.4 releases tomorrow.

**Comment by Pyrdacor** [comment]
I updated the 1.4 release so please download again and check if it works. If not please feel free to re-open this issue and let me know.

**Comment by Tosh79** [comment]
Small update on this: works like a charm, if using the packages under "releases". The ones linked in the "readme.md"-File are still the unfixed ones, however.

Thanks for the quick fix! Looking forward finishing a game, I got as a christmas gift 28 years ago ;-)

**Comment by Pyrdacor** [comment]
This is strange. Should be the same file. Are you sure about it?

**Comment by Tosh79** [comment]
Heya... yepp! Just checked it out again. The mac-bundle 1.4 from the readme.md-file does not work. These are the link-targets:

- readme.md: 
  - https://github.com/Pyrdacor/Ambermoon.net/raw/master/Downloads/1.4/Ambermoon.net-Mac-Bundle.zip
  - About 52 MB
  - App-File directly within zip-archive

- releases-page:
  - https://github.com/Pyrdacor/Ambermoon.net/releases/download/v1.4.0/Ambermoon.net-Mac-Bundle.zip
  - About 49 MB
  - App-File within an ambermoon.net folder when extracted

Best regards!

**Comment by Pyrdacor** [comment]
Thanks for checking. I guess I made a mistake while packing. Will fix this soon.

**Comment by Pyrdacor** [comment]
Links should work now. Can someone please re-check? Thanks.

**Comment by Tosh79** [comment]
Hi @Pyrdacor ,

sorry to say this, but the mac-bundle under the link in the readme.md (https://github.com/Pyrdacor/Ambermoon-Releases/raw/main/Ambermoon.net/1.4/Ambermoon.net-Mac-Bundle.zip) is still not working.

Best regards!

**Comment by Pyrdacor** [comment]
@Tosh79  Hm I checked again and the file you said is working (49MB) is binary identical to the one from your last post. So either both work or none of them. Or maybe it is caused by the folder? But I can't believe that.

**Comment by Tosh79** [comment]
Well... i inspected both files with the osx finder.

<img width="626" alt="Screenshot" src="https://user-images.githubusercontent.com/40628353/148984444-3636a529-51ef-49b2-b529-d34781c27288.png">

The file on the left is the one from the readme.md, which is not working. The file on the right is downloaded from the releases page. They are quite different in size. In both cases, I downloaded the "mac-bundle"-File.

**Comment by Pyrdacor** [comment]
Ok I checked again. What you see on Mac is the whole folder. The sizes of the main executable ("Ambermoon.net.app/Contents/MacOS/Ambermoon.net") is exactly the same. The size difference stems from the fact that the zip from the readme contains additional stuff like a walkthrough, an english manual or the rune page. Other than that both zips are identical. Maybe Mac can't handle additional files inside the "Contents/MacOS" sub-path?

**Comment by Pyrdacor** [comment]
@Tosh79 A friend of mine tested the 1.4 version from the readme and could run it without problems. He said it is important to right click and choose run and accept the warning when you run it for the first time. Maybe this helps? I am not that familiar with Mac unfortunately.

**Comment by Pyrdacor** [comment]
If you still have problems, please let me know.
